In [1]:
# Dependencies
import requests

url = "http://api.worldbank.org/v2/"
format = "json"

# Get country information in JSON format
countries_response = requests.get(f"{url}countries?format={format}").json()

# First element is general information, second is countries themselves
countries = countries_response[1]

In [3]:
print(f"{url}countries?format={format}")

http://api.worldbank.org/v2/countries?format=json

In [8]:
import pandas as pd
pd.DataFrame(countries_response[1])

,adminregion,capitalCity,id,incomeLevel,iso2Code,latitude,lendingType,longitude,name,region
0,"{'id': '', 'iso2code': '', 'value': ''}",Oranjestad,ABW,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",AW,12.5167,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",-70.0167,Aruba,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati..."
1,"{'id': 'SAS', 'iso2code': '8S', 'value': 'Sout...",Kabul,AFG,"{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...",AF,34.5228,"{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",69.1761,Afghanistan,"{'id': 'SAS', 'iso2code': '8S', 'value': 'Sout..."
2,"{'id': '', 'iso2code': '', 'value': ''}",,AFR,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",A9,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,Africa,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
3,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...",Luanda,AGO,"{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...",AO,-8.81155,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",13.242,Angola,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-..."
4,"{'id': 'ECA', 'iso2code': '7E', 'value': 'Euro...",Tirane,ALB,"{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...",AL,41.3317,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",19.8172,Albania,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro..."
5,"{'id': '', 'iso2code': '', 'value': ''}",Andorra la Vella,AND,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",AD,42.5075,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",1.5218,Andorra,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro..."
6,"{'id': '', 'iso2code': '', 'value': ''}",,ANR,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",L5,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,Andean Region,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
7,"{'id': '', 'iso2code': '', 'value': ''}",,ARB,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",1A,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,Arab World,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
8,"{'id': '', 'iso2code': '', 'value': ''}",Abu Dhabi,ARE,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",AE,24.4764,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",54.3705,United Arab Emirates,"{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd..."
9,"{'id': '', 'iso2code': '', 'value': ''}",Buenos Aires,ARG,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",AR,-34.6118,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",-58.4173,Argentina,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati..."
10,"{'id': 'ECA', 'iso2code': '7E', 'value': 'Euro...",Yerevan,ARM,"{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...",AM,40.1596,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",44.509,Armenia,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro..."
11,"{'id': 'EAP', 'iso2code': '4E', 'value': 'East...",Pago Pago,ASM,"{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...",AS,-14.2846,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",-170.691,American Samoa,"{'id': 'EAS', 'iso2code': 'Z4', 'value': 'East..."
12,"{'id': '', 'iso2code': '', 'value': ''}",Saint John's,ATG,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",AG,17.1175,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",-61.8456,Antigua and Barbuda,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati..."
13,"{'id': '', 'iso2code': '', 'value': ''}",Canberra,AUS,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",AU,-35.282,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",149.129,Australia,"{'id': 'EAS', 'iso2code': 'Z4', 'value': 'East..."
14,"{'id': '', 'iso2code': '', 'value': ''}",Vienna,AUT,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",AT,48.2201,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",16.3798,Austria,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro..."
15,"{'id': 'ECA', 'iso2code': '7E', 'value': 'Euro...",Baku,AZE,"{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...",AZ,40.3834,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",49.8932,Azerbaijan,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro..."
16,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...",Bujumbura,BDI,"{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...",BI,-3.3784,"{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",29.3639,Burundi,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-..."
17,"{'id': '', 'iso2code': '', 'value': ''}",,BEA,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",B4,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,East Asia & Pacific (IBRD-only countries),"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
18,"{'id': '', 'iso2code': '', 'value': ''}",,BEC,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",B7,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,Europe & Central Asia (IBRD-only countries),"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
19,"{'id': '', 'iso2code': '', 'value': ''}",Brussels,BEL,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",BE,50.8371,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",4.36761,Belgium,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro..."
20,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...",Porto-Novo,BEN,"{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...",BJ,6.4779,"{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",2.6323,Benin,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-..."
21,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...",Ouagadougou,BFA,"{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...",BF,12.3605,"{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",-1.53395,Burkina Faso,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-..."
22,"{'id': 'SAS', 'iso2code': '8S', 'value': 'Sout...",Dhaka,BGD,"{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...",BD,23.7055,"{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",90.4113,Bangladesh,"{'id': 'SAS', 'iso2code': '8S', 'value': 'Sout..."
23,"{'id': 'ECA', 'iso2code': '7E', 'value': 'Euro...",Sofia,BGR,"{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...",BG,42.7105,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",23.3238,Bulgaria,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro..."
24,"{'id': '', 'iso2code': '', 'value': ''}",,BHI,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",B1,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,IBRD countries classified as high income,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
25,"{'id': '', 'iso2code': '', 'value': ''}",Manama,BHR,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",BH,26.1921,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",50.5354,Bahrain,"{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd..."
26,"{'id': '', 'iso2code': '', 'value': ''}",Nassau,BHS,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",BS,25.0661,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",-77.339,"Bahamas, The","{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati..."
27,"{'id': 'ECA', 'iso2code': '7E', 'value': 'Euro...",Sarajevo,BIH,"{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...",BA,43.8607,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",18.4214,Bosnia and Herzegovina,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro..."
28,"{'id': '', 'iso2code': '', 'value': ''}",,BLA,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",B2,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,Latin America & the Caribbean (IBRD-only count...,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
29,"{'id': 'ECA', 'iso2code': '7E', 'value': 'Euro...",Minsk,BLR,"{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...",BY,53.9678,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",27.5766,Belarus,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro..."
30,"{'id': 'LAC', 'iso2code': 'XJ', 'value': 'Lati...",Belmopan,BLZ,"{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...",BZ,17.2534,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",-88.7713,Belize,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati..."
31,"{'id': '', 'iso2code': '', 'value': ''}",,BMN,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",B3,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,Middle East & North Africa (IBRD-only countries),"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
32,"{'id': '', 'iso2code': '', 'value': ''}",Hamilton,BMU,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",BM,32.3293,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",-64.706,Bermuda,"{'id': 'NAC', 'iso2code': 'XU', 'value': 'Nort..."
33,"{'id': 'LAC', 'iso2code': 'XJ', 'value': 'Lati...",La Paz,BOL,"{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...",BO,-13.9908,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",-66.1936,Bolivia,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati..."
34,"{'id': 'LAC', 'iso2code': 'XJ', 'value': 'Lati...",Brasilia,BRA,"{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...",BR,-15.7801,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",-47.9292,Brazil,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati..."
35,"{'id': '', 'iso2code': '', 'value': ''}",Bridgetown,BRB,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",BB,13.0935,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",-59.6105,Barbados,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati..."
36,"{'id': '', 'iso2code': '', 'value': ''}",Bandar Seri Begawan,BRN,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",BN,4.94199,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",114.946,Brunei Darussalam,"{'id': 'EAS', 'iso2code': 'Z4', 'value': 'East..."
37,"{'id': '', 'iso2code': '', 'value': ''}",,BSS,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",B6,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,Sub-Saharan Africa (IBRD-only countries),"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
38,"{'id': 'SAS', 'iso2code': '8S', 'value': 'Sout...",Thimphu,BTN,"{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...",BT,27.5768,"{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",89.6177,Bhutan,"{'id': 'SAS', 'iso2code': '8S', 'value': 'Sout..."
39,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...",Gaborone,BWA,"{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...",BW,-24.6544,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",25.9201,Botswana,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-..."
40,"{'id': '', 'iso2code': '', 'value': ''}",,CAA,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",C9,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,Sub-Saharan Africa (IFC classification),"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
41,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...",Bangui,CAF,"{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...",CF,5.63056,"{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",21.6407,Central African Republic,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-..."
42,"{'id': '', 'iso2code': '', 'value': ''}",Ottawa,CAN,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",CA,45.4215,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",-75.6919,Canada,"{'id': 'NAC', 'iso2code': 'XU', 'value': 'Nort..."
43,"{'id': '', 'iso2code': '', 'value': ''}",,CEA,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",C4,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,East Asia and the Pacific (IFC classification),"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
44,"{'id': '', 'iso2code': '', 'value': ''}",,CEB,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",B8,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,Central Europe and the Baltics,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
45,"{'id': '', 'iso2code': '', 'value': ''}",,CEU,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...",C5,,"{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,Europe and Central Asia (IFC classification),"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre..."
46,"{'id': '', 'iso2code': '', 'value': ''}",Bern,CHE,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",CH,46.948,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",7.44821,Switzerland,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro..."
47,"{'id': '', 'iso2code': '', 'value': ''}",,CHI,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",JG,,"{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",,Channel Islands,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro..."
48,"{'id': '', 'iso2code': '', 'value': ''}",Santiago,CHL,"{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...",CL,-33.475,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",-70.6475,Chile,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati..."
49,"{'id': 'EAP', 'iso2code': '4E', 'value': 'East...",Beijing,CHN,"{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...",CN,40.0495,"{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",116.286,China,"{'id': 'EAS', 'iso2code': 'Z4', 'value': 'East..."

In [2]:
# Report the names
for country in countries:
    print(country["name"])

Aruba
Afghanistan
Africa
Angola
Albania
Andorra
Andean Region
Arab World
United Arab Emirates
Argentina
Armenia
American Samoa
Antigua and Barbuda
Australia
Austria
Azerbaijan
Burundi
East Asia & Pacific (IBRD-only countries)
Europe & Central Asia (IBRD-only countries)
Belgium
Benin
Burkina Faso
Bangladesh
Bulgaria
IBRD countries classified as high income
Bahrain
Bahamas, The
Bosnia and Herzegovina
Latin America & the Caribbean (IBRD-only countries)
Belarus
Belize
Middle East & North Africa (IBRD-only countries)
Bermuda
Bolivia
Brazil
Barbados
Brunei Darussalam
Sub-Saharan Africa (IBRD-only countries)
Bhutan
Botswana
Sub-Saharan Africa (IFC classification)
Central African Republic
Canada
East Asia and the Pacific (IFC classification)
Central Europe and the Baltics
Europe and Central Asia (IFC classification)
Switzerland
Channel Islands
Chile
China